@IsTest
public with sharing class SMS_ShopsExternalControllerTest {



//    @isTest testGetShops(){
//        SMS_Shop__c smsShop = new SMS_Shop__c();
//        smsShop.Country__c = 'Poland';
//        smsShop.Name = 'TestName';
//        SMS_Util.Shop searchParamsShop = new SMS_Util.Shop();
//        searchParamsShop.Name = 'tes';
//        searchParamsShop.Country = 'Poland';
//
//        List<SMS_Util.Shop> res = new List<SMS_Util.Shop>();
//        res = SMS_ShopsExternalController.getShops();
//        System.assert(!res.isEmpty());
//    }

}